#!/usr/bin/env node

const { runImhotap } = require('../testutil')

process.chdir(__dirname)

runImhotap()
runImhotap('-q')
runImhotap('--quiet')
runImhotap('--concurrency', '1')
runImhotap('--concurrency', '0')
runImhotap('--concurrency', '10')
runImhotap('--files', 'test/test-*.js')
runImhotap('-f', 'test/test-1.js')
runImhotap('-r', 'tap-colorize')
runImhotap('--reporter', 'tap-colorize')
runImhotap('--reporter', 'tap-nyan')
runImhotap('--reporter', 'cat')
